services:
  crossword-backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"

  crossword-frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_ORIGIN=crossword-backend:8000
    depends_on:
      - crossword-backend

networks:
  default:
    name: crossword-net
    driver: bridge
